a = int(input("Enter the 1st number: "))
b = int(input("Enter the 2nd number: "))
c = int(input("Enter the 3rd number: "))
d = int(input("Enter the 4th number: "))
e = int(input("Enter the 5th number: "))
average = ((a+b+c+d+e)/5)
print("Average: ", average)